[package]
name = "many_time_pad"
version = "0.1.0"
authors = ["nczhu <nicole@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.1"